
/****** Object:  Database [VivekStudy]    Script Date: 23-03-2025 17:38:49 ******/
CREATE DATABASE [VivekStudy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VivekStudy', FILENAME = N'F:\data\VivekStudy.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VivekStudy_log', FILENAME = N'F:\log\VivekStudy_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [VivekStudy] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VivekStudy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VivekStudy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VivekStudy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VivekStudy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VivekStudy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VivekStudy] SET ARITHABORT OFF 
GO

ALTER DATABASE [VivekStudy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VivekStudy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VivekStudy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VivekStudy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VivekStudy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VivekStudy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VivekStudy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VivekStudy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VivekStudy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VivekStudy] SET  ENABLE_BROKER 
GO

ALTER DATABASE [VivekStudy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VivekStudy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VivekStudy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VivekStudy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VivekStudy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VivekStudy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VivekStudy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VivekStudy] SET RECOVERY FULL 
GO

ALTER DATABASE [VivekStudy] SET  MULTI_USER 
GO

ALTER DATABASE [VivekStudy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VivekStudy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VivekStudy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VivekStudy] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VivekStudy] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VivekStudy] SET QUERY_STORE = OFF
GO

USE [VivekStudy]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [VivekStudy] SET  READ_WRITE 
GO


